require 'linearly/mixins/flow_builder'
require 'linearly/mixins/reducer'
require 'linearly/errors/broken_contract'
require 'linearly/errors/state_not_returned'
require 'linearly/flow'
require 'linearly/runner'
require 'linearly/step/dynamic'
require 'linearly/step/static'
require 'linearly/validation'
require 'linearly/version'

require 'statefully'
